<a href="https://colab.research.google.com/github/changsksu/IMSE_Data_Science/blob/main/Diagnosis_of_T2_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This code demonstrates how you can identify which dimension contribute the most in T2 statistics
---
Note that this code should work for the Phase I of the control charting. Use the mean vector mean1 and covariance matrix cov1 estimated from the Phase I data set for the Phase II charting.

In [ ]:
# Import required libraries
from scipy.stats import beta
from scipy.stats import f
from scipy.stats import multivariate_normal
import numpy as np
import statistics
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns
import pandas as pd
plt.style.use('seaborn-colorblind')

# Montgomery Intro to SQC 8ed 2020 Wiley. pp 469 Example

---

consider the standardized mean vector of [0,0,0] for p=3 and correlation matrix of 0.9 correlation element everywhere

In [ ]:
mu=np.array([0,0,0])
covAll = np.array([[1,0.9,0.9], [0.9,1,0.9], [0.9,0.9,1]])
#Case A:
x =np.array([2,0,0]) - mu
# compute the 
matinv = np.linalg.inv(covAll)
T2_all=matinv.dot(x.T).dot(x)
print("T2_all=", T2_all)
# d1 
x1 =np.array(x[1:3])
covminus1=covAll[1:3, 1:3]
matinv1 = np.linalg.inv(covminus1)
T2_1=matinv1.dot(x1.T).dot(x1)
d1=T2_all - T2_1
print("T2(1)=", T2_1)
print("d1=", d1)
# d2
x2 =np.array([x[0],x[2]])
covminus2=np.array([covAll[0,0], covAll[0,2], covAll[2,0], covAll[2,2]])
covminus2=np.reshape(covminus2, (2,2))
matinv2 = np.linalg.inv(covminus2)
T2_2=matinv2.dot(x2.T).dot(x2)
d2=T2_all - T2_2
print("T2(2)=", T2_2)
print("d2=", d2)
# d3
x3 =np.array(x[0:2])
covminus3=covAll[0:2, 0:2]
matinv3 = np.linalg.inv(covminus3)
T2_3=matinv3.dot(x3.T).dot(x3)
d3=T2_all - T2_3
print("T2(3)=", T2_3)
print("d3=", d3)

T2_all= 27.142857142857146
T2(1)= 0.0
d1= 27.142857142857146
T2(2)= 21.052631578947373
d2= 6.090225563909772
T2(3)= 21.052631578947373
d3= 6.090225563909772


In [ ]:
covAll = np.array([[1,0.9,0.9], [0.9,1,0.9], [0.9,0.9,1]])
#Case B:
x =np.array([1,1,-1]) 
# compute the 
matinv = np.linalg.inv(covAll)
T2_all=matinv.dot(x.T).dot(x)
print("T2_all=", T2_all)
# d1 
x1 =np.array(x[1:3])
covminus1=covAll[1:3, 1:3]
matinv1 = np.linalg.inv(covminus1)
T2_1=matinv1.dot(x1.T).dot(x1)
d1=T2_all - T2_1
print("T2(1)=", T2_1)
print("d1=", d1)
# d2
x2 =np.array([x[0],x[2]])
covminus2=np.array([covAll[0,0], covAll[0,2], covAll[2,0], covAll[2,2]])
covminus2=np.reshape(covminus2, (2,2))
matinv2 = np.linalg.inv(covminus2)
T2_2=matinv2.dot(x2.T).dot(x2)
d2=T2_all - T2_2
print("T2(2)=", T2_2)
print("d2=", d2)
# d3
x3 =np.array(x[0:2])
covminus3=covAll[0:2, 0:2]
matinv3 = np.linalg.inv(covminus3)
T2_3=matinv3.dot(x3.T).dot(x3)
d3=T2_all - T2_3
print("T2(3)=", T2_3)
print("d3=", d3)

T2_all= 26.78571428571428
T2(1)= 20.000000000000007
d1= 6.785714285714274
T2(2)= 20.000000000000007
d2= 6.785714285714274
T2(3)= 1.0526315789473681
d3= 25.733082706766915


In [ ]:
# retrive data for Drug Effect data k=3
data = pd.read_csv('https://raw.githubusercontent.com/changsksu/K-State-IMSE641/master/Hotelling_T2.csv', sep=',', na_values=".")
#generate the Phase I data using filter
#use the first 18 observations to setup the control charts
dataI= [data[['Fever', 'Pressure', 'Aches']][data['ID'] == "Placebo"]]

#retrieve the Phase II data
dataII= [data[['Fever', 'Pressure', 'Aches']][data['ID'] == "Drug"]]

#all data points; the data type is a list
dataAll=[data[['Fever', 'Pressure', 'Aches']]]


In [ ]:
# this np.reshape convert the list dataI into the proper subgroup and m=30
# sample size n=5 is used for X-bar and R or X-bar and S chart
x1=np.reshape(dataI, (18,3))
x2=np.reshape(dataII, (20,3))
x3=np.reshape(dataAll, (38,3))

In [ ]:
# compute column means
mean1=np.mean(x1, axis=0)
mean2=np.mean(x2, axis=0)
diff=mean1-mean2 #this is the difference in the mean vectors
diff


array([ 0.75444444, -6.17222222,  1.81111111])

In [ ]:
# glean the mean vector without the first dimension
diffminus1=diff[1:3]
diffminus1

array([-6.17222222,  1.81111111])

In [ ]:
# glean the mean vector without the second dimension
diffminus2=np.array([diff[0],diff[2]])
diffminus2

array([0.75444444, 1.81111111])

In [ ]:
# glean the mean vector without the third dimension
diffminus3=diff[0:2]
diffminus3

array([ 0.75444444, -6.17222222])

In [ ]:
# compute the covariance matrix assuming the covariance stay the same
covAll = np.cov(x3.T)
covAll

array([[  1.47877667, -11.09046942,   2.32475107],
       [-11.09046942, 177.17496444, -35.65291607],
       [  2.32475107, -35.65291607,  28.40682788]])

In [ ]:
# compute the inverse of the covariance matrix with p=3
matinvAll = np.linalg.inv(covAll)
matinvAll

array([[ 1.27526853,  0.07870267, -0.00558677],
       [ 0.07870267,  0.0124084 ,  0.00913271],
       [-0.00558677,  0.00913271,  0.04712232]])

In [ ]:
# compute the T2 values with all dimensions
T2_all=matinvAll.dot(diff.T).dot(diff)
T2_all

0.4007245804210801

In [ ]:
# compute the T2 values with all dimensions
covminus1=covAll[0:2, 0:2]
matinv1 = np.linalg.inv(covminus1)
covminus1

array([[  1.47877667, -11.09046942],
       [-11.09046942, 177.17496444]])

In [ ]:
T2_1=matinv1.dot(diffminus1.T).dot(diffminus1)
T2_1

46.80893340539867

In [ ]:
d1=T2_all - T2_1
d1

-46.40820882497759

In [ ]:
# compute the T2 values with all dimensions except the second & d2
covminus2=np.array([covAll[0,0], covAll[0,2], covAll[2,0], covAll[2,2]])
covminus2=np.reshape(covminus2, (2,2))
matinv2 = np.linalg.inv(covminus2)
T2_2=matinv2.dot(diffminus2.T).dot(diffminus2)
d2=T2_all - T2_2
print(T2_2)
print("d2=", d2)

0.40068837764699694
d2= 3.620277408317163e-05


In [ ]:
# compute the T2 values with all dimensions except the third & d3
covminus3=covAll[1:3, 1:3]
matinv3 = np.linalg.inv(covminus3)
T2_3=matinv3.dot(diffminus3.T).dot(diffminus3)
d3=T2_all - T2_3
print(T2_3)
print("d3=", d3)


1.7102873471071467
d3= -1.3095627666860665


# Your turn: try other cases x=(1,-1,0) and (0.5,0.5,1)

---
Draw conclusions of these cases. Which cases do the proposed method fails to address?
