<a href="https://colab.research.google.com/github/changsksu/IMSE_Data_Science/blob/main/PCA_Eigen_values_and_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA - Eigen Values and Vectors

---
This code demonstrates how eigen values and vectors are computed based on a covariance matrix. Ref. https://medium.com/luca-chuangs-bapm-notes/principal-component-analysis-pca-using-python-scikit-learn-48c4c13e49af

In [ ]:
# Import required libraries
from scipy.stats import beta
from scipy.stats import f
from scipy.stats import multivariate_normal
import numpy as np
import statistics
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import seaborn as sns
import pandas as pd
plt.style.use('seaborn-colorblind')

In [ ]:
# the famous iris data set
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])
df.head()

sepal length  sepal width  petal length  petal width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
# Separating out the features
x = df.loc[:, features].values
# Separating out the target
y = df.loc[:,['target']].values
# Standardizing the features
x = sc.fit_transform(x)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# compute the eigen vector and values
cov_mat = np.cov(x.T)

# From this covariance matrix, caluclate the Eigenvalues and the Eigenvectors
eigen_vals, eigen_vecs = np.linalg.eig(cov_mat)
print("Eigen values=", eigen_vals)
print("Eigen vectors=", eigen_vecs)

Eigen values= [2.93035378 0.92740362 0.14834223 0.02074601]
Eigen vectors= [[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]


In [ ]:
eigen_sum=eigen_vals.sum()
weights=eigen_vals/eigen_sum
print("Weights of Eigen Values =", weights)

Weights of Eigen Values = [0.72770452 0.23030523 0.03683832 0.00515193]


Note that the first two eigen values account for more than 95% of all variation in the data set