<a href="https://colab.research.google.com/github/changsksu/IMSE_Data_Science/blob/main/Python_matrix_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook outlines the use of np array and matrix operations.  
Ref. https://numpy.org/doc/stable/reference/generated/numpy.mat.html 

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
 #convert an array into a matrix
 m = np.asmatrix(x)
 m

matrix([[1, 2],
        [3, 4]])

In [ ]:
x[0,0] = 5
x

array([[5, 2],
       [3, 4]])

In [ ]:
m[0,1]

2

In [ ]:
# note that the element in m changed as well since m is based on array x
# when x is changed so is matrix m
m[0,0]

5

In [ ]:
# transpose
mp=m.transpose()
mp

matrix([[1, 3],
        [2, 4]])

In [ ]:
# matrix multiplication
mpm=np.matmul(mp, m)
mpm

matrix([[10, 14],
        [14, 20]])

In [ ]:
# matrix inverse
print(np.linalg.inv(mpm))

[[ 5.  -3.5]
 [-3.5  2.5]]
